// <auto-generated />
using System;
using CK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CK.Core.Entities.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAirportTransfer")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CK.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CK.Core.Entities.StandardBooking", b =>
                {
                    b.HasBaseType("CK.Core.Entities.Booking");

                    b.Property<decimal>("CleaningFee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("StandardBookings", (string)null);
                });

            modelBuilder.Entity("CK.Core.Entities.SuiteBooking", b =>
                {
                    b.HasBaseType("CK.Core.Entities.Booking");

                    b.Property<string>("ButlerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VipCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SuiteBookings", (string)null);
                });

            modelBuilder.Entity("CK.Core.Entities.StandardBooking", b =>
                {
                    b.HasOne("CK.Core.Entities.Booking", null)
                        .WithOne()
                        .HasForeignKey("CK.Core.Entities.StandardBooking", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CK.Core.Entities.SuiteBooking", b =>
                {
                    b.HasOne("CK.Core.Entities.Booking", null)
                        .WithOne()
                        .HasForeignKey("CK.Core.Entities.SuiteBooking", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
